# tasks/main.yml
- name: Ensure namespace exists
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ postgres_namespace }}"
    state: present

- name: Create SeaweedFS S3 credentials secret
  kubernetes.core.k8s:
    state: present
    namespace: "{{ postgres_namespace }}"
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ backup_secret }}"
        namespace: "{{ postgres_namespace }}"
      type: Opaque
      data:
        AWS_ACCESS_KEY_ID: "{{ seaweed_access_key | b64encode }}"
        AWS_SECRET_ACCESS_KEY: "{{ seaweed_secret_key | b64encode }}"

- name: Deploy PostgreSQL headless service
  kubernetes.core.k8s:
    state: present
    namespace: "{{ postgres_namespace }}"
    template: "{{ role_path }}/templates/postgres-service.yml.j2"

- name: Deploy PostgreSQL statefulset
  kubernetes.core.k8s:
    state: present
    namespace: "{{ postgres_namespace }}"
    template: "{{ role_path }}/templates/postgres-statefulset.yml.j2"

- name: Create backup CronJob
  kubernetes.core.k8s:
    state: present
    namespace: "{{ postgres_namespace }}"
    template: "{{ role_path }}/templates/backup-cronjob.yml.j2"
